server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: Movie-backend
  datasource:
    url: jdbc:postgresql://db.matjcxyattaokehxibbk.supabase.co:5432/postgres
    username: postgres
    password: E,!kA@x65J?377f
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
flask:
  api:
    url: http://localhost:5000
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

vnpay:
  vnp_TmnCode: "I7X8N6N3"
  vnp_HashSecret: "W7X9S0T3H5K2L1M4N8P9"
  vnp_Url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  vnp_ReturnUrl: "http://localhost:5173/payment-callback"